# Cognizance2020
![MAGICAL MATHEMATICS](https://d1e4pidl3fu268.cloudfront.net/285e6758-de6d-4130-819d-4688508b227f/mathsmagiccover.crop_595x446_0,0.preview.PNG)
# **PYSCHIC MATHS**
---
## *WELCOME TO THIS MAGICAL WORLD OF MATHEMATICS*

> ### **Description**
* This is  a simple game or you can say a simple trick of mathematics where we guess the number which the player thinks....
* Here a simple function of randomize() is used.

> ### **Rules to play**
1. Only think of positive integers.
2. Keep a calculator if you need.
3. Do not diclose the numbers
4. The least BE HONEST!!
